const LISTINGS = [
  {
    id: "arusha-hotel",
    name: "The Arusha Hotel",
    category: "hotel",
    location: "Sokoine Road, Arusha CBD",
    price: 90,
    rating: 4.6,
    featured: true,
    phone: "+255754000001",
    email: "reservations@arushahotel.example",
    summary: "Classic city-centre hotel with garden, pool and conference facilities.",
    summary_sw: "Hoteli ya kati ya jiji yenye bustani, bwawa la kuogelea na vyumba vya mikutano.",
    description: "Set right in the heart of Arusha on Sokoine Road, The Arusha Hotel is a long-standing favourite for travellers heading to Kilimanjaro and the northern parks. Rooms are spacious and air-conditioned, the garden restaurant serves local and international dishes, and the pool is a welcome stop after a long flight. Walking distance to banks, pharmacies and the clock tower.",
    description_sw: "iko katikati ya Arusha kwenye barabara ya Sokoine. Ni hoteli ya muda mrefu inayopendwa na wasafiri wanaoelekea Kilimanjaro na hifadhi za kaskazini. Vyumba ni pana na vyenye hewa, mgahawa wa bustani unahudumia chakula cha asili na kimataifa, na bwawa la kuogelea ni mapumziko mazuri baada ya safari ndefu. Umbali mfupi kutoka benki, maduka ya dawa na saa ya jiji.",
    amenities: ["wifi", "pool", "breakfast", "parking", "ac", "restaurant"],
    imageColor: "#087A6A"
  },
  {
    id: "mount-meru-hotel",
    name: "Mount Meru Hotel",
    category: "hotel",
    location: "Sokoine Road, Arusha",
    price: 110,
    rating: 4.5,
    featured: true,
    phone: "+255754000002",
    email: "info@mountmeruhotel.example",
    summary: "Four-star hotel with views of Mount Meru, ideal for pre-safari stays.",
    summary_sw: "Hoteli ya nyota nne yenye mwonekano wa Mlima Meru, inafaa kwa wageni wanaoanza safari.",
    description: "A landmark Arusha hotel sitting on several acres with a clear view of Mount Meru. Large pool, tennis courts, spa and multiple restaurants make it a comfortable base for families and tour groups arriving for AFCON 2027. Ten minutes from Arusha Airport and close to the Uhuru Monument.",
    description_sw: "Hoteli maarufu ya Arusha iliyo kwenye ekari nyingi na mwonekano wazi wa Mlima Meru. Bwawa kubwa la kuogelea, tenisi, spa na migahawa mingi inafaa kwa familia na vikundi vya watalii wanaokuwa kwa AFCON 2027. Dakika 10 kutoka Uwanja wa Ndege wa Arusha na karibu na Kumbukumbu ya Uhuru.",
    amenities: ["wifi", "pool", "breakfast", "parking", "ac", "restaurant", "gym"],
    imageColor: "#1B5E7A"
  },
  {
    id: "panama-garden",
    name: "Panama Garden Resort",
    category: "hotel",
    location: "Njiro Road, Arusha",
    price: 70,
    rating: 4.3,
    featured: false,
    phone: "+255754000003",
    email: "booking@panamagarden.example",
    summary: "Quiet garden resort a short drive from the city centre.",
    summary_sw: "Makazi tulivu ya bustani umbali mfupi kutoka kati ya jiji.",
    description: "A relaxed resort-style property set back from the road in Njiro, with mature gardens, an outdoor pool and spacious family rooms. Popular with tour groups because of its large parking area and conference hall. Boda-boda and taxi pickup can be arranged at reception.",
    description_sw: "Sehemu tulivu yenye bustani nje ya barabara Njiro, yenye bustani zilizokomaa, bwawa la nje na vyumba vya familia. Inapendwa na vikundi vya watalii kwa sababu ya maegesho makubwa na ukumbi wa mikutano. Mapokezi ya boda-boda na taksi yanapatikana katika mapokezi.",
    amenities: ["wifi", "pool", "breakfast", "parking", "ac", "restaurant"],
    imageColor: "#D9A441"
  },
  {
    id: "tulia-apartments",
    name: "Tulia Serviced Apartments",
    category: "apartment",
    location: "Njiro, Arusha",
    price: 55,
    rating: 4.4,
    featured: true,
    phone: "+255754000004",
    email: "stay@tuliaapartments.example",
    summary: "Self-catering one and two-bedroom apartments with Wi-Fi and parking.",
    summary_sw: "Vyumba vya kulala viwili na kimoja vyenye jiko, Wi-Fi na maegesho.",
    description: "Fully equipped apartments for fans and teams who want their own space. Each unit has a kitchen, living area, fast Wi-Fi and a balcony. Weekly rates available for longer stays during the tournament. Secure parking and 24-hour security on site.",
    description_sw: "Apartimenti kamili kwa mashabiki na timu zinazotaka nafasi yao. Kila chumba kina jiko, sehemu ya kuishi, Wi-Fi ya haraka na balkoni. Bei ya wiki inapatikana kwa wanaokaa muda mrefu wakati wa mashindano. Maegesho salama na usalama wa saa 24.",
    amenities: ["wifi", "kitchen", "parking", "ac", "balcony"],
    imageColor: "#087A6A"
  },
  {
    id: "kibo-court",
    name: "Kibo Court Apartments",
    category: "apartment",
    location: "Moshono, Arusha",
    price: 65,
    rating: 4.7,
    featured: false,
    phone: "+255754000005",
    email: "hello@kibocourt.example",
    summary: "Modern gated apartments in quiet Moshono with mountain views.",
    summary_sw: "Apartimenti za kisasa zenye lango Moshono zenye mwonekano wa milima.",
    description: "Newer apartments in a gated compound in Moshono, a calm suburb above Arusha. Sun-lit living rooms, well-equipped kitchens and a shared garden. Ideal for small groups travelling together for matches, with easy access to the main road into town.",
    description_sw: "Apartimenti mpya katika eneo lenye lango Moshono, mtaa tulivu juu ya Arusha. Sehemu za kuishi zenye mwanga, jiko zilizokamilika na bustani ya pamoja. Inafaa kwa vikundi vidogo vinavyosafiri pamoja kwenda mechi, na upatikanaji rahisi wa barabara kuu kwenda mjini.",
    amenities: ["wifi", "kitchen", "parking", "ac", "garden"],
    imageColor: "#1B5E7A"
  },
  {
    id: "city-lodge-studio",
    name: "City Pulse Studios",
    category: "apartment",
    location: "Arusha CBD",
    price: 40,
    rating: 4.1,
    featured: false,
    phone: "+255754000006",
    email: "book@citypulsestudios.example",
    summary: "Affordable studios in town, walking distance to shops and buses.",
    summary_sw: "Vyumba vya bei nafuu mjini, umbali wa kutembea kwenda maduka na mabasi.",
    description: "Compact, clean studios right in the central business district — the budget-friendly option for solo visitors who want to be close to everything. Shared rooftop terrace, daily housekeeping and secure door locks.",
    description_sw: "Vyumba vidogo, safisi katikati ya biashara ya jiji — chaguo la bei nafuu kwa wasafiri wa pekee wanaotaka kuwa karibu na kila kitu. Uwanja wa paa wa pamoja, usafi wa kila siku na milango salama.",
    amenities: ["wifi", "ac", "parking"],
    imageColor: "#D9A441"
  },
  {
    id: "kilimanjaro-transfers",
    name: "Kilimanjaro Airport Transfers",
    category: "transport",
    location: "Kilimanjaro International Airport (JRO)",
    price: 45,
    rating: 4.8,
    featured: true,
    phone: "+255754000007",
    email: "dispatch@kilitransfers.example",
    summary: "Private airport pickups to Arusha, Moshi and safari lodges.",
    summary_sw: "Usafiri wa kibinafsi kutoka uwanja wa ndege kwenda Arusha, Moshi na migahawa ya safari.",
    description: "Meet-and-greet service at Kilimanjaro International Airport with fixed prices to Arusha, Moshi and any lodge on the northern circuit. Air-conditioned SUVs and minivans, flight tracking, and English/Kiswahili speaking drivers. Available 24/7 during the tournament.",
    description_sw: "Huduma ya kupokea katika Uwanja wa Ndege wa Kilimanjaro kwa bei maalum kwenda Arusha, Moshi au migahawa yoyote ya safari ya kaskazini. Gari la AC na van, ufuatiliaji wa ndege, na madereva wazungumzaji Kiingereza/Kiswahili. Inapatikana siku 24 wakati wa mashindano.",
    amenities: ["ac", "english", "luggage", "childseat"],
    imageColor: "#087A6A"
  },
  {
    id: "arusha-safari-shuttles",
    name: "Arusha Safari Shuttles",
    category: "transport",
    location: "Arusha Town Centre",
    price: 60,
    rating: 4.5,
    featured: false,
    phone: "+255754000008",
    email: "bookings@arushashuttles.example",
    summary: "Shared and private 4x4 shuttles to parks, stadiums and intercity routes.",
    summary_sw: "Usafiri wa pamoja na wa kibinafsi wa 4x4 kwenda hifadhi, viwanja na miji.",
    description: "Open-roof Land Cruisers and minibuses for match-day transfers, city tours and trips to Tarangire, Ngorongoro and the Serengeti. Group discounts for supporters' clubs travelling together.",
    description_sw: "Land Cruiser zenye paa wazi na minibasi kwa usafiri wa siku ya mechi, matembezi ya jiji na safari kwenda Tarangire, Ngorongoro na Serengeti. Punguzo la vikundi kwa vyama vya mashabiki vinavyosafiri pamoja.",
    amenities: ["ac", "english", "luggage", "groupdiscount"],
    imageColor: "#1B5E7A"
  },
  {
    id: "boda-boda-arusha",
    name: "T-Pulse Boda & Bajaj",
    category: "transport",
    location: "Arusha CBD & Njiro",
    price: 5,
    rating: 4.2,
    featured: false,
    phone: "+255754000009",
    email: "ride@tpulseboda.example",
    summary: "Fast boda-boda and bajaj rides across Arusha, fixed stadium routes.",
    summary_sw: "Usafiri wa haraka wa boda-boda na bajaj katika Arusha, njia maalum za viwanja.",
    description: "Helmet-equipped boda-boda and bajaj riders covering the CBD, Njiro, Moshono and Sakina. Fixed fares to the stadium on match days so you never get overcharged. Riders are registered and reachable on WhatsApp.",
    description_sw: "Waendeshaji wenye kofia ya usalama wa boda-boda na bajaj wanaofikia CBD, Njiro, Moshono na Sakina. Bei maalum kwenda uwanja wa mechi siku za mchezo ili usilipwe kupita kiasi. Waendeshaji wamesajiliwa na unaweza kuwapata kwa WhatsApp.",
    amenities: ["whatsapp", "helmet", "fixedprice"],
    imageColor: "#D9A441"
  },
  {
    id: "clock-tower-grill",
    name: "Clock Tower Grill House",
    category: "restaurant",
    location: "Sokoine Road, Arusha CBD",
    price: 12,
    rating: 4.5,
    featured: true,
    phone: "+255754000010",
    email: "table@clocktowergrill.example",
    summary: "Flame-grilled nyama choma and Tanzanian classics beside the Clock Tower.",
    summary_sw: "Nyama choma na chakula cha Kitanzania kilichochemshwa kando ya saa ya jiji.",
    description: "A lively Arusha grill house a few steps from the Clock Tower. Nyama choma, pilau, chipsi mayai and cold drinks served in a busy open-air setting — the kind of place fans end up at after a match. Family tables available, and the kitchen stays open late on match nights.",
    description_sw: "Mgahawa maarufu wa Arusha wa kuchomea nyama, hatua chache kutoka saa ya jiji. Nyama choma, pilau, chipsi mayai na vinywaji baridi katika eneo wazi lenye msisimko — mahali pa mashabiki kwenda baada ya mechi. Meza za familia zinapatikana, na jiko hufungua mpaka kauche siku za mechi.",
    amenities: ["outdoor", "family", "veg", "wifi"],
    imageColor: "#C0392B"
  },
  {
    id: "kaskazi-coffee-house",
    name: "Kaskazi Coffee House",
    category: "restaurant",
    location: "Njiro Road, Arusha",
    price: 8,
    rating: 4.6,
    featured: false,
    phone: "+255754000011",
    email: "hello@kaskazicoffee.example",
    summary: "Speciality coffee, breakfasts and light lunches in a leafy courtyard.",
    summary_sw: "Kahawa maalum, chakula cha asubuhi na cha mchana katika bustani ya mti.",
    description: "A calm courtyard café serving single-origin Kilimanjaro and Arusha coffees, fresh breakfasts and light lunches. Fast Wi-Fi and plenty of plug points make it a favourite with remote workers and anyone recovering from a long flight. Vegetarian and vegan options always on the menu.",
    description_sw: "Mgahawa wa amani unaohudumia kahawa za Kilimanjaro na Arusha, chakula cha asubuhi chenye ubora na cha mchana. Wi-Fi ya haraka na miunganiko mingi ya umeme imefanya iwapendwe na wanaofanya kazi mbali na yeyote anayetaka kupumzika baada ya safari ndefu. Chaguo za mboga na vegan zinapatikana daima.",
    amenities: ["wifi", "outdoor", "veg", "breakfast"],
    imageColor: "#087A6A"
  },
  {
    id: "meru-terrace",
    name: "Meru Terrace Restaurant",
    category: "restaurant",
    location: "Moshono Ridge, Arusha",
    price: 18,
    rating: 4.4,
    featured: false,
    phone: "+255754000012",
    email: "reservations@meruterrace.example",
    summary: "Rooftop dining with sunset views over Mount Meru.",
    summary_sw: "Chakula cha jioni kwenye paa chenye mwonekano wa jua kizama Mlima Meru.",
    description: "An open-air terrace restaurant on the Moshono ridge serving grilled fish, steaks and Swahili dishes against a wide view of Mount Meru. Live acoustic music on weekends, reserved tables for groups, and a sunset slot worth booking ahead during the tournament.",
    description_sw: "Mgahawa wa paa ulio wazi Moshono unaohudumia samaki wa kuchoma, nyama na chakula cha Kiswahili chenye mwonekano mpana wa Mlima Meru. Muziki wa akustiki wikendi, meza maalum kwa vikundi, na wakati wa jua kizama unaostahili kuagiza mapema wakati wa mashindano.",
    amenities: ["outdoor", "live_music", "family", "restaurant"],
    imageColor: "#1B5E7A"
  },
  {
    id: "kilimanjaro-day-hike",
    name: "Kilimanjaro Day Hike — Mandara Hut",
    category: "experience",
    location: "Marangu Gate, Kilimanjaro",
    price: 95,
    rating: 4.8,
    featured: false,
    phone: "+255754000013",
    email: "treks@kilihike.example",
    summary: "Guided day hike on Kilimanjaro to Mandara Hut and back.",
    summary_sw: "Mapumziko ya siku kwenye Kilimanjaro hadi Mandara Hut na kurudi.",
    description: "A full-day guided hike from Marangu Gate through rainforest to Mandara Hut at 2,720m and back — a taste of Kilimanjaro without the multi-day commitment. Park fees, lunch, drinking water, porter support and an experienced mountain guide are all included. Pick-up from anywhere in Arusha.",
    description_sw: "Hatembea ya siku nzima kutoka Marangu Gate kupitia msitu wa mbwa hadi Mandara Hut kwenye mita 2,720 na kurudi — onji ya Kilimanjaro bila kuchukua siku nyingi. Ada za hifadhi, chakula cha mchana, maji ya kunywa, wasaidizi na mwongozo mtaalamu wamejumuishwa. Tunakuchukua popote Arusha.",
    amenities: ["guide", "lunch", "transport_included", "gear"],
    imageColor: "#111111"
  },
  {
    id: "materuni-waterfalls",
    name: "Materuni Waterfalls & Coffee Experience",
    category: "experience",
    location: "Materuni Village, Kilimanjaro",
    price: 45,
    rating: 4.7,
    featured: true,
    phone: "+255754000014",
    email: "trips@materuniwalks.example",
    summary: "Waterfalls, natural pools and a coffee-farm tour with a local guide.",
    summary_sw: "Majukwaa ya maji, mabwawa asilia na kutembelea bustani ya kahawa na mwongozo.",
    description: "A half-day trip to the Chagga village of Materuni: a 40-minute walk to a 150m waterfall, a swim in the natural pool if you're brave enough, then hands-on coffee processing with a local family — from cherry to cup. Transport from Arusha and lunch included.",
    description_sw: "Safari ya nusu siku kwenda kijiji cha Materuni: kutembea dakika 40 kwenda majukwaa ya maji ya mita 150, kuogelea kwenye bwawa asilia ukiwa na ujasiri, kisha kushiriki kuchakata kahawa na familia ya wenyeji — kutoka chrizi hadi kikombe. Usafiri kutoka Arusha na chakula cha mchana vimejumuishwa.",
    amenities: ["guide", "lunch", "transport_included", "family"],
    imageColor: "#087A6A"
  },
  {
    id: "arusha-park-safari",
    name: "Arusha National Park Day Safari",
    category: "experience",
    location: "Arusha National Park",
    price: 120,
    rating: 4.6,
    featured: false,
    phone: "+255754000015",
    email: "safari@arushadaysafari.example",
    summary: "Full-day game drive with crater-rim walk and picnic lunch.",
    summary_sw: "Safari ya siku nzima yenye kutembea kando ya krater na chakula cha mchana.",
    description: "A full day in Arusha National Park — giraffe, zebra, buffalo, colobus monkeys and flamingos on the Momella lakes, plus an optional walk on the Ngurdoto crater rim with an armed ranger. Open 4x4 vehicle, picnic lunch and park fees included. Back in Arusha by sunset.",
    description_sw: "Siku nzima katika Hifadhi ya Taifa ya Arusha — twiga, punda milia, nyati, kima-watu wa mgogoro na flamingo kwenye mabwawa ya Momella, pamoja na kutembea hiari kando ya krater ya Ngurdoto na askari wa silaha. Gari la 4x4 wazi, chakula cha mchana na ada za hifadhi vimejumuishwa. Unarudi Arusha kabla ya jua kizama.",
    amenities: ["guide", "lunch", "transport_included", "gear"],
    imageColor: "#D9A441"
  }
];

const AMENITY_LABELS = {
  wifi: "Wi-Fi",
  pool: "Swimming pool",
  breakfast: "Breakfast included",
  parking: "Free parking",
  ac: "Air conditioning",
  restaurant: "Restaurant",
  gym: "Gym",
  kitchen: "Kitchen",
  balcony: "Balcony",
  garden: "Garden",
  english: "English-speaking driver",
  luggage: "Luggage space",
  childseat: "Child seats",
  groupdiscount: "Group discount",
  whatsapp: "WhatsApp booking",
  helmet: "Helmets provided",
  fixedprice: "Fixed price",
  outdoor: "Outdoor seating",
  veg: "Vegetarian options",
  live_music: "Live music",
  family: "Family friendly",
  guide: "Professional guide",
  lunch: "Lunch included",
  transport_included: "Transport included",
  gear: "Gear provided"
};

const AMENITY_LABELS_SW = {
  wifi: "Wi-Fi",
  pool: "Bwawa la kuogelea",
  breakfast: "Chakula cha asubuhi",
  parking: "Maegesho ya bure",
  ac: "Moto wa hewa",
  restaurant: "Mgahawa",
  gym: "Chumba cha mazoezi",
  kitchen: "Jiko",
  balcony: "Balkoni",
  garden: "Bustani",
  english: "Dereva anayezungumza Kiingereza",
  luggage: "Nafasi ya mizigo",
  childseat: "Viti vya watoto",
  groupdiscount: "Punguzo la kikundi",
  whatsapp: "Kuagiza kwa WhatsApp",
  helmet: "Kofia za usalama",
  fixedprice: "Bei iliyoshikwa",
  outdoor: "Viti vya nje",
  veg: "Chaguo za mboga",
  live_music: "Muziki moja kwa moja",
  family: "Kinafaa familia",
  guide: "Mwongozo mtaalamu",
  lunch: "Chakula cha mchana kimejumuishwa",
  transport_included: "Usafiri kimejumuishwa",
  gear: "Vifaa vimetolewa"
};
